import os

from engine.placement import EdgeConnection
from engine.tile import Tile, ShapeType
from engine.city import CityPlacement
from engine.monastery import MonasteryPlacement
from engine.road import RoadPlacement
from engine.field import FieldPlacement, EdgeConnection

tile_types = {
    "A": Tile(
        tile_type="A",
        borders=[ShapeType.FIELD, ShapeType.FIELD, ShapeType.ROAD, ShapeType.FIELD],
        monastery_placement=MonasteryPlacement(meeple_xy=[0, 0]),
        city_placements=[],
        road_placements=[RoadPlacement(connections=[EdgeConnection.D],
                                       meeple_xy=[0, 25])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.UL, EdgeConnection.UR, EdgeConnection.RU,
                                                      EdgeConnection.RD, EdgeConnection.DL, EdgeConnection.DR,
                                                      EdgeConnection.LU, EdgeConnection.LD],
                                         meeple_xy=[20, -20],
                                         city_connections=[])],
        rotations=[0]
    ),
    "B": Tile(
        tile_type="B",
        borders=[ShapeType.FIELD, ShapeType.FIELD, ShapeType.FIELD, ShapeType.FIELD],
        monastery_placement=MonasteryPlacement(meeple_xy=[0, 0]),
        city_placements=[],
        road_placements=[],
        field_placements=[FieldPlacement(connections=[EdgeConnection.UL, EdgeConnection.UR, EdgeConnection.RU,
                                                      EdgeConnection.RD, EdgeConnection.DL, EdgeConnection.DR,
                                                      EdgeConnection.LU, EdgeConnection.LD],
                                         meeple_xy=[20, -20],
                                         city_connections=[])],
        rotations=[0]
    ),
    "C": Tile(
        tile_type="C",
        borders=[ShapeType.CITY, ShapeType.CITY, ShapeType.CITY, ShapeType.CITY],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U, EdgeConnection.D, EdgeConnection.R,
                                                    EdgeConnection.L],
                                       shield=True,
                                       meeple_xy=[0, 0])],
        road_placements=[],
        field_placements=[],
        rotations=[0, 1, 2, 3]
    ),
    "D": Tile(
        tile_type="D",
        borders=[ShapeType.CITY, ShapeType.ROAD, ShapeType.FIELD, ShapeType.ROAD],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U],
                                       meeple_xy=[0, -22],
                                       shield=False)],
        road_placements=[RoadPlacement(connections=[EdgeConnection.R, EdgeConnection.L],
                                       meeple_xy=[-3, 7])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.RU, EdgeConnection.LU],
                                         city_connections=[0],
                                         meeple_xy=[-15, -9]),
                          FieldPlacement(connections=[EdgeConnection.RD, EdgeConnection.LD, EdgeConnection.DL,
                                                      EdgeConnection.DR],
                                         meeple_xy=[15, 16],
                                         city_connections=[])],
        rotations=[0, 1, 2, 3]

    ),
    "E": Tile(
        tile_type="E",
        borders=[ShapeType.CITY, ShapeType.FIELD, ShapeType.FIELD, ShapeType.FIELD],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U],
                                       meeple_xy=[0, -22],
                                       shield=False)],
        road_placements=[],
        field_placements=[FieldPlacement(connections=[EdgeConnection.RU, EdgeConnection.RD, EdgeConnection.DL,
                                                      EdgeConnection.DR, EdgeConnection.LU, EdgeConnection.LD],
                                         meeple_xy=[0, 10],
                                         city_connections=[0])],
        rotations=[0, 1, 2, 3]
    ),
    "F": Tile(
        tile_type="F",
        borders=[ShapeType.FIELD, ShapeType.CITY, ShapeType.FIELD, ShapeType.CITY],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.R, EdgeConnection.L],
                                       meeple_xy=[0, 0],
                                       shield=True)],
        road_placements=[],
        field_placements=[FieldPlacement(connections=[EdgeConnection.UL, EdgeConnection.UR],
                                         meeple_xy=[0, -22],
                                         city_connections=[0]),
                          FieldPlacement(connections=[EdgeConnection.DL, EdgeConnection.DR],
                                         meeple_xy=[0, 26],
                                         city_connections=[0])],
        rotations=[0, 1, 2, 3]
    ),
    "G": Tile(
        tile_type="G",
        borders=[ShapeType.FIELD, ShapeType.CITY, ShapeType.FIELD, ShapeType.CITY],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.R, EdgeConnection.L],
                                       meeple_xy=[0, 0],
                                       shield=False)],
        road_placements=[],
        field_placements=[FieldPlacement(connections=[EdgeConnection.UL, EdgeConnection.UR],
                                         meeple_xy=[0, -22],
                                         city_connections=[0]),
                          FieldPlacement(connections=[EdgeConnection.DL, EdgeConnection.DR],
                                         meeple_xy=[0, 26],
                                         city_connections=[0])],
        rotations=[0, 1, 2, 3]
    ),
    "H": Tile(
        tile_type="H",
        borders=[ShapeType.CITY, ShapeType.FIELD, ShapeType.CITY, ShapeType.FIELD],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U],
                                       meeple_xy=[0, -22],
                                       shield=False),
                         CityPlacement(connections=[EdgeConnection.D],
                                       meeple_xy=[0, 22],
                                       shield=False)],
        road_placements=[],
        field_placements=[FieldPlacement(connections=[EdgeConnection.RU, EdgeConnection.RD, EdgeConnection.LU,
                                                      EdgeConnection.LD],
                                         meeple_xy=[0, 0],
                                         city_connections=[0, 1])],
        rotations=[0, 1, 2, 3]
    ),
    "I": Tile(
        tile_type="I",
        borders=[ShapeType.CITY, ShapeType.FIELD, ShapeType.FIELD, ShapeType.CITY],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U],
                                       meeple_xy=[0, -22],
                                       shield=False),
                         CityPlacement(connections=[EdgeConnection.L],
                                       meeple_xy=[-22, 0],
                                       shield=False)],
        road_placements=[],
        field_placements=[FieldPlacement(connections=[EdgeConnection.RU, EdgeConnection.RD, EdgeConnection.DL,
                                                      EdgeConnection.DR],
                                         meeple_xy=[5, 5],
                                         city_connections=[0, 1])],
        rotations=[0, 1, 2, 3]
    ),
    "J": Tile(
        tile_type="J",
        borders=[ShapeType.CITY, ShapeType.ROAD, ShapeType.ROAD, ShapeType.FIELD],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U],
                                       meeple_xy=[0, -22],
                                       shield=False)],
        road_placements=[RoadPlacement(connections=[EdgeConnection.R, EdgeConnection.D],
                                       meeple_xy=[2, 2])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.RU, EdgeConnection.LU, EdgeConnection.LD,
                                                      EdgeConnection.DL],
                                         meeple_xy=[-22, -4],
                                         city_connections=[0]),
                          FieldPlacement(connections=[EdgeConnection.RD, EdgeConnection.DR],
                                         meeple_xy=[22, 22],
                                         city_connections=[]),
                          ],
        rotations=[0, 1, 2, 3]
    ),
    "K": Tile(
        tile_type="K",
        borders=[ShapeType.CITY, ShapeType.FIELD, ShapeType.ROAD, ShapeType.ROAD],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U],
                                       meeple_xy=[0, -22],
                                       shield=False)],
        road_placements=[RoadPlacement(connections=[EdgeConnection.L, EdgeConnection.D],
                                       meeple_xy=[7, -2])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.RU, EdgeConnection.RD, EdgeConnection.DR,
                                                      EdgeConnection.LU],
                                         meeple_xy=[22, 10],
                                         city_connections=[0]),
                          FieldPlacement(connections=[EdgeConnection.LD, EdgeConnection.DL],
                                         meeple_xy=[-15, 15],
                                         city_connections=[]),
                          ],
        rotations=[0, 1, 2, 3]
    ),
    "L": Tile(
        tile_type="L",
        borders=[ShapeType.CITY, ShapeType.ROAD, ShapeType.ROAD, ShapeType.ROAD],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U],
                                       meeple_xy=[0, -22],
                                       shield=False)],
        road_placements=[RoadPlacement(connections=[EdgeConnection.R],
                                       meeple_xy=[22, 0]),
                         RoadPlacement(connections=[EdgeConnection.L],
                                       meeple_xy=[-22, 0]),
                         RoadPlacement(connections=[EdgeConnection.D],
                                       meeple_xy=[0, 22])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.RU, EdgeConnection.LU],
                                         meeple_xy=[-25, -15],
                                         city_connections=[0]),
                          FieldPlacement(connections=[EdgeConnection.LD, EdgeConnection.DL],
                                         meeple_xy=[-20, 20],
                                         city_connections=[]),
                          FieldPlacement(connections=[EdgeConnection.RD, EdgeConnection.DR],
                                         meeple_xy=[20, 20],
                                         city_connections=[])],
        rotations=[0, 1, 2, 3]
    ),
    "M": Tile(
        tile_type="M",
        borders=[ShapeType.CITY, ShapeType.CITY, ShapeType.FIELD, ShapeType.FIELD],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U, EdgeConnection.R],
                                       meeple_xy=[12, -12],
                                       shield=True)],
        road_placements=[],
        field_placements=[FieldPlacement(connections=[EdgeConnection.LU, EdgeConnection.LD, EdgeConnection.DL,
                                                      EdgeConnection.DR],
                                         meeple_xy=[-12, 12],
                                         city_connections=[0])],
        rotations=[0, 1, 2, 3]
    ),
    "N": Tile(
        tile_type="N",
        borders=[ShapeType.CITY, ShapeType.CITY, ShapeType.FIELD, ShapeType.FIELD],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U, EdgeConnection.R],
                                       meeple_xy=[12, -12],
                                       shield=False)],
        road_placements=[],
        field_placements=[FieldPlacement(connections=[EdgeConnection.LU, EdgeConnection.LD, EdgeConnection.DL,
                                                      EdgeConnection.DR],
                                         meeple_xy=[-12, 12],
                                         city_connections=[0])],
        rotations=[0, 1, 2, 3]
    ),
    "O": Tile(
        tile_type="O",
        borders=[ShapeType.CITY, ShapeType.ROAD, ShapeType.ROAD, ShapeType.CITY],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U, EdgeConnection.L],
                                       meeple_xy=[-12, -12],
                                       shield=True)],
        road_placements=[RoadPlacement(connections=[EdgeConnection.R, EdgeConnection.D],
                                       meeple_xy=[9, 9])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.RU, EdgeConnection.DL],
                                         meeple_xy=[-12, 20],
                                         city_connections=[0]),
                          FieldPlacement(connections=[EdgeConnection.RD, EdgeConnection.DR],
                                         meeple_xy=[22, 22],
                                         city_connections=[])],
        rotations=[0, 1, 2, 3]
    ),
    "P": Tile(
        tile_type="P",
        borders=[ShapeType.CITY, ShapeType.ROAD, ShapeType.ROAD, ShapeType.CITY],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U, EdgeConnection.L],
                                       meeple_xy=[-12, -12],
                                       shield=False)],
        road_placements=[RoadPlacement(connections=[EdgeConnection.R, EdgeConnection.D],
                                       meeple_xy=[9, 9])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.RU, EdgeConnection.DL],
                                         meeple_xy=[-12, 20],
                                         city_connections=[0]),
                          FieldPlacement(connections=[EdgeConnection.RD, EdgeConnection.DR],
                                         meeple_xy=[22, 22],
                                         city_connections=[])],
        rotations=[0, 1, 2, 3]
    ),
    "Q": Tile(
        tile_type="Q",
        borders=[ShapeType.CITY, ShapeType.CITY, ShapeType.FIELD, ShapeType.CITY],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U, EdgeConnection.L, EdgeConnection.R],
                                       meeple_xy=[0, -10],
                                       shield=True)],
        road_placements=[],
        field_placements=[FieldPlacement(connections=[EdgeConnection.DL, EdgeConnection.DR],
                                         meeple_xy=[0, 22],
                                         city_connections=[0])],
        rotations=[0, 1, 2, 3]
    ),
    "R": Tile(
        tile_type="R",
        borders=[ShapeType.CITY, ShapeType.CITY, ShapeType.FIELD, ShapeType.CITY],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U, EdgeConnection.L, EdgeConnection.R],
                                       meeple_xy=[0, -10],
                                       shield=False)],
        road_placements=[],
        field_placements=[FieldPlacement(connections=[EdgeConnection.DL, EdgeConnection.DR],
                                         meeple_xy=[0, 22],
                                         city_connections=[0])],
        rotations=[0, 1, 2, 3]
    ),
    "S": Tile(
        tile_type="S",
        borders=[ShapeType.CITY, ShapeType.CITY, ShapeType.ROAD, ShapeType.CITY],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U, EdgeConnection.L, EdgeConnection.R],
                                       meeple_xy=[0, -10],
                                       shield=True)],
        road_placements=[RoadPlacement(connections=[EdgeConnection.D],
                                       meeple_xy=[0, 20])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.DL],
                                         meeple_xy=[-15, 23],
                                         city_connections=[0]),
                          FieldPlacement(connections=[EdgeConnection.DR],
                                         meeple_xy=[15, 23],
                                         city_connections=[0])
                          ],
        rotations=[0, 1, 2, 3]
    ),
    "T": Tile(
        tile_type="T",
        borders=[ShapeType.CITY, ShapeType.CITY, ShapeType.ROAD, ShapeType.CITY],
        monastery_placement=None,
        city_placements=[CityPlacement(connections=[EdgeConnection.U, EdgeConnection.L, EdgeConnection.R],
                                       meeple_xy=[0, -10],
                                       shield=False)],
        road_placements=[RoadPlacement(connections=[EdgeConnection.D],
                                       meeple_xy=[0, 20])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.DL],
                                         meeple_xy=[-15, 23],
                                         city_connections=[0]),
                          FieldPlacement(connections=[EdgeConnection.DR],
                                         meeple_xy=[15, 23],
                                         city_connections=[0])
                          ],
        rotations=[0, 1, 2, 3]
    ),
    "U": Tile(
        tile_type="U",
        borders=[ShapeType.ROAD, ShapeType.FIELD, ShapeType.ROAD, ShapeType.FIELD],
        monastery_placement=None,
        city_placements=[],
        road_placements=[RoadPlacement(connections=[EdgeConnection.U, EdgeConnection.D],
                                       meeple_xy=[0, 0])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.UR, EdgeConnection.RU, EdgeConnection.RD,
                                                      EdgeConnection.DR],
                                         meeple_xy=[19, 0],
                                         city_connections=[]),
                          FieldPlacement(connections=[EdgeConnection.UL, EdgeConnection.LU, EdgeConnection.LD,
                                                      EdgeConnection.DL],
                                         meeple_xy=[-19, 0],
                                         city_connections=[])],
        rotations=[0, 1]
    ),
    "V": Tile(
        tile_type="V",
        borders=[ShapeType.FIELD, ShapeType.FIELD, ShapeType.ROAD, ShapeType.ROAD],
        monastery_placement=None,
        city_placements=[],
        road_placements=[RoadPlacement(connections=[EdgeConnection.L, EdgeConnection.D],
                                       meeple_xy=[-10, 5])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.LU, EdgeConnection.UR, EdgeConnection.UL,
                                                      EdgeConnection.RU, EdgeConnection.RD, EdgeConnection.DR],
                                         meeple_xy=[10, -10],
                                         city_connections=[]),
                          FieldPlacement(connections=[EdgeConnection.LD, EdgeConnection.DL],
                                         meeple_xy=[-20, 17],
                                         city_connections=[])],
        rotations=[0, 1, 2, 3]
    ),
    "W": Tile(
        tile_type="W",
        borders=[ShapeType.FIELD, ShapeType.ROAD, ShapeType.ROAD, ShapeType.ROAD],
        monastery_placement=None,
        city_placements=[],
        road_placements=[RoadPlacement(connections=[EdgeConnection.R],
                                       meeple_xy=[20, 0]),
                         RoadPlacement(connections=[EdgeConnection.L],
                                       meeple_xy=[-20, 0]),
                         RoadPlacement(connections=[EdgeConnection.D],
                                       meeple_xy=[0, 20])],
        field_placements=[FieldPlacement(connections=[EdgeConnection.LU, EdgeConnection.UR, EdgeConnection.UL,
                                                      EdgeConnection.RU],
                                         meeple_xy=[0, -20],
                                         city_connections=[]),
                          FieldPlacement(connections=[EdgeConnection.LD, EdgeConnection.DL],
                                         meeple_xy=[-22, 20],
                                         city_connections=[]),
                          FieldPlacement(connections=[EdgeConnection.RD, EdgeConnection.DR],
                                         meeple_xy=[22, 20],
                                         city_connections=[])],
        rotations=[0, 1, 2, 3]
    ),
    "X": Tile(
        tile_type="X",
        borders=[ShapeType.ROAD, ShapeType.ROAD, ShapeType.ROAD, ShapeType.ROAD],
        monastery_placement=None,
        city_placements=[],
        road_placements=[RoadPlacement(connections=[EdgeConnection.R],
                                       meeple_xy=[20, 0]),
                         RoadPlacement(connections=[EdgeConnection.L],
                                       meeple_xy=[-20, 0]),
                         RoadPlacement(connections=[EdgeConnection.D],
                                       meeple_xy=[0, 20]),
                         RoadPlacement(connections=[EdgeConnection.U],
                                       meeple_xy=[0, -20])
                         ],
        field_placements=[FieldPlacement(connections=[EdgeConnection.LU, EdgeConnection.UL],
                                         meeple_xy=[-20, -20],
                                         city_connections=[]),
                          FieldPlacement(connections=[EdgeConnection.RU, EdgeConnection.UR],
                                         meeple_xy=[20, -20],
                                         city_connections=[]),
                          FieldPlacement(connections=[EdgeConnection.LD, EdgeConnection.DL],
                                         meeple_xy=[-20, 20],
                                         city_connections=[]),
                          FieldPlacement(connections=[EdgeConnection.RD, EdgeConnection.DR],
                                         meeple_xy=[20, 20],
                                         city_connections=[])],
        rotations=[0, 1, 2, 3]
    )
}

##
# Setting D=4 as we will use one as the initial tile.
tile_counts = {
    "A": 2,
    "B": 4,
    "C": 1,
    "D": 4,
    "E": 5,
    "F": 2,
    "G": 1,
    "H": 3,
    "I": 2,
    "J": 3,
    "K": 3,
    "L": 3,
    "M": 2,
    "N": 3,
    "O": 2,
    "P": 3,
    "Q": 1,
    "R": 3,
    "S": 2,
    "T": 1,
    "U": 8,
    "V": 9,
    "W": 4,
    "X": 1
}
